version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/my-nodejs-app
permissions:
  - object: /var/www/my-nodejs-app
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: scripts/create_directory.sh
      timeout: 300
      runas: root
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
