version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Building the application"
      - npm run build --if-present
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'  # Adjust this pattern to include specific files or directories as artifacts
  base-directory: 'build'  # Change this if your build output is in a different directory
